// <auto-generated />
namespace ggak_final_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addedcoordinateswithDbGeometry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcoordinateswithDbGeometry));
        
        string IMigrationMetadata.Id
        {
            get { return "201412120651376_added-coordinates-with-DbGeometry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
