// <auto-generated />
namespace ggak_final_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class removedrequiredonlatitudelongitudeurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedrequiredonlatitudelongitudeurl));
        
        string IMigrationMetadata.Id
        {
            get { return "201412160558264_removed-required-on-latitude-longitude-url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
